/**
 * Civilizace podle herního id (1 = Britons … v pořadí, v jakém je hra zavedla).
 * Názvy jsou z jazykového souboru hry (řetězec 10270 + id), vygenerováno
 * 7. 9. 2026. Null v sestavě znamená „libovolná“ — hráč si vybere sám.
 */
export const CIVILIZACE: Record<number, string> = {
  1: "Britons",
  2: "Franks",
  3: "Goths",
  4: "Teutons",
  5: "Japanese",
  6: "Chinese",
  7: "Byzantines",
  8: "Persians",
  9: "Saracens",
  10: "Turks",
  11: "Vikings",
  12: "Mongols",
  13: "Celts",
  14: "Spanish",
  15: "Aztecs",
  16: "Maya",
  17: "Huns",
  18: "Koreans",
  19: "Italians",
  20: "Hindustanis",
  21: "Inca",
  22: "Magyars",
  23: "Slavs",
  24: "Portuguese",
  25: "Ethiopians",
  26: "Malians",
  27: "Berbers",
  28: "Khmer",
  29: "Malay",
  30: "Burmese",
  31: "Vietnamese",
  32: "Bulgarians",
  33: "Tatars",
  34: "Cumans",
  35: "Lithuanians",
  36: "Burgundians",
  37: "Sicilians",
  38: "Poles",
  39: "Bohemians",
  40: "Dravidians",
  41: "Bengalis",
  42: "Gurjaras",
  43: "Romans",
  44: "Armenians",
  45: "Georgians",
  46: "Achaemenids",
  47: "Athenians",
  48: "Spartans",
  49: "Shu",
  50: "Wu",
  51: "Wei",
  52: "Jurchens",
  53: "Khitans",
  54: "Macedonians",
  55: "Thracians",
  56: "Puru",
  57: "Muisca",
  58: "Mapuche",
  59: "Tupi",
};

export function nazevCivilizace(id: number | null): string {
  if (id === null) return "libovolná";
  return CIVILIZACE[id] ?? `civilizace č. ${id}`;
}
