/**
 * Taunty ze hry (uživatel 13. 9. 2026: „chat bude taky podporovat taunty,
 * například 1 = Yes, 11 = smích“). Zpráva, která je jen číslem z téhle
 * tabulky, se ukáže jako taunt s jeho textem. Texty jsou z herního souboru
 * `resources/en/strings/key-value/key-value-strings-utf8.txt` (klíče 11400
 * až 11504 = taunty 1 až 105), převzaté doslova.
 *
 * Zvuky všech 105 tauntů jsou v `web/src/assets/taunty/taunt-NN.mp3`
 * (z `wwise/en/Base.pck`, viz `nastroje/zvuky/taunty.py`); prohlížeč je hraje
 * v App.tsx místo cinknutí, i autorovi.
 */
export const TAUNTY: Readonly<Record<number, string>> = {
  1: "Yes",
  2: "No",
  3: "Food, please",
  4: "Wood, please",
  5: "Gold, please",
  6: "Stone, please",
  7: "Ahh",
  8: "All hail",
  9: "Oooh",
  10: "Back to Age 1",
  11: "Laugh",
  12: "Being rushed",
  13: "Blame your isp",
  14: "Start the game",
  15: "Don't Point That Thing",
  16: "Enemy Sighted",
  17: "It Is Good",
  18: "I Need a Monk",
  19: "Long Time No Siege",
  20: "My granny",
  21: "Nice Town I'll Take It",
  22: "Quit Touchin",
  23: "Raiding Party",
  24: "Dadgum",
  25: "Smite Me",
  26: "The Wonder",
  27: "You play 2 hours",
  28: "You Should See the Other Guy",
  29: "Roggan",
  30: "Wololo",
  31: "Attack an Enemy Now",
  32: "Cease Creating Extra Villagers",
  33: "Create Extra Villagers",
  34: "Build a Navy",
  35: "Stop Building a Navy",
  36: "Wait for My Signal to Attack",
  37: "Build a Wonder",
  38: "Give Me Your Extra Resources",
  39: "Ally",
  40: "Enemy",
  41: "Neutral",
  42: "What Age Are You In?",
  43: "What is your strategy?",
  44: "How many resources do you have?",
  45: "Retreat now!",
  46: "Flare the location of your army.",
  47: "Attack in direction of the flared location.",
  48: "I'm being attacked, please help!",
  49: "Build a forward base at the flared location.",
  50: "Build a fortification at the flared location.",
  51: "Keep your army close to mine and fight with me.",
  52: "Build a market at the flared location.",
  53: "Rebuild your base at the flared location.",
  54: "Build a wall between the two flared locations.",
  55: "Build a wall around your town.",
  56: "Train units which counter the enemy's army.",
  57: "Stop training counter units.",
  58: "Prepare to send me all your resources so I can vanquish our foes!",
  59: "Stop sending me extra resources.",
  60: "Prepare to train a large army, I will send you as many resources as I can spare.",
  61: "Attack player 1!",
  62: "Attack player 2!",
  63: "Attack player 3!",
  64: "Attack player 4!",
  65: "Attack player 5!",
  66: "Attack player 6!",
  67: "Attack player 7!",
  68: "Attack player 8!",
  69: "Delete the object on the flared location.",
  70: "Delete your excess villagers.",
  71: "Delete excess warships.",
  72: "Focus on training infantry units.",
  73: "Focus on training cavalry units.",
  74: "Focus on training ranged units.",
  75: "Focus on training warships.",
  76: "Attack the enemy with Militia.",
  77: "Attack the enemy with Archers.",
  78: "Attack the enemy with Skirmishers.",
  79: "Attack the enemy with a mix of Archers and Skirmishers.",
  80: "Attack the enemy with Scout Cavalry.",
  81: "Attack the enemy with Men-at-Arms.",
  82: "Attack the enemy with Eagle Scouts.",
  83: "Attack the enemy with Towers.",
  84: "Attack the enemy with Crossbowmen.",
  85: "Attack the enemy with Cavalry Archers.",
  86: "Attack the enemy with Unique Units.",
  87: "Attack the enemy with Knights.",
  88: "Attack the enemy with Battle Elephants.",
  89: "Attack the enemy with Scorpions.",
  90: "Attack the enemy with Monks.",
  91: "Attack the enemy with Monks and Mangonels.",
  92: "Attack the enemy with Eagle Warriors.",
  93: "Attack the enemy with Halberdiers and Rams.",
  94: "Attack the enemy with Elite Eagle Warriors.",
  95: "Attack the enemy with Arbalests.",
  96: "Attack the enemy with Champions.",
  97: "Attack the enemy with Galleys.",
  98: "Attack the enemy with Fire Galleys.",
  99: "Attack the enemy with Demolition Rafts.",
  100: "Attack the enemy with War Galleys.",
  101: "Attack the enemy with Fire Ships.",
  102: "Attack the enemy with Unique Warships.",
  103: "Use an Onager to cut down trees at the flared location.",
  104: "Don't resign!",
  105: "You can resign again.",
};

/** Číslo tauntu ze zprávy, nebo null (zpráva musí být jen to číslo). */
export function cisloTauntu(text: string): number | null {
  const m = /^\s*(\d{1,3})\s*$/.exec(text);
  if (!m) return null;
  const n = Number(m[1]);
  return n in TAUNTY ? n : null;
}
